###
#  .profile.d/00_default.conf
#
#  Basic shell setup, loaded before anything else thanks to the 00 prefix.
###

# Overwrite the default PATH variable
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# Load user binary directories into path
if [ -d "${HOME}/bin" ]
then
	PATH="${HOME}/bin:${PATH}"
fi

if [ -d "${HOME}/.local/bin" ]
then
	PATH="${HOME}/.local/bin:${PATH}"
fi

# Set umask to 007 (default directory mode 770, file mode 660)
# Better for shared groups, like with compose stacks that have volume mounts
umask 007
